export default {
  dashboard: "Dashboard",
  signIn: "Sign in",
  newHere: "New Here?",
  createAnAccount: "Create an Account",
  email: "Email",
  password: "Password",
  continue: "Continue",
  pleaseWait: "Please wait",
  alreadyHaveAnAccount: "Already have an account?",
  signInHere: "Sign in here",
  firstName: "First Name",
  lastName: "Last Name",
  phoneNumber: "Phone Number",
  passwordConfirmation: "Confirm Password",
  useSymbols:
    "Use 8 or more characters with a mix of letters, numbers & symbols.",
  submit: "Submit",
  websiteSettings: "Website Settings",
  setupSettings: "Setup Your Website Settings",
  marketSettings: "Market Settings",
  marketSetup: "Setup Your Market Settings",
  langAndCurr: "Languages and Currencies",
  langAndCurrSettings: "Market languages and currencies settings",
  marketIdentity: "Market Identity",
  marketIdentitySettings: "Set Your Market Identity",
  catAndTags: "Categories & Tags",
  catAndTagsSettings: "Set Your Categories and Tags",
  completed: "Completed",
  woah: "Woah, we are here",
  back: "Back",
  subdomain: "Sub Domain",
  domain: "Domain",
  marketLocation: "Market Location",
  country: "Country",
  city: "City",
  area: "Area",
  location: "Location",
  languages: "Languages",
  currencies: "Currencies",
  logo: "Logo",
  pleaseEnterMarketAllLangs:
    "Please Enter Maket name and descriptions in all languages you have choosen",
  fieldRequired: "field is required",
  name: "Name",
  description: "Description",
  categories: "Categories",
  tags: "Tags",
  youAreDone: "Your Are Done!",
  search: "Search",
  productLabels: "Product Labels",
  connectedProductsCount: "Number Of Connected Products",
  connectedShopsCount: "Number Of Connected Shops",
  addLabel: "Add Label",
  labels: "Labels",
  icon: "Icon",
  code: "Code",
  order: "Order",
  backgroundColor: "Background Color",
  textColor: "Text Color",
  delete: "Delete",
  update: "Update",
  add: "Add",
  save: "Save",
  select: "Select Item ",
  isPublishedOnJetOrderApp: "is Published On JetOrder App",
  isPublishedOnShopLink: "is Published On ShopLink",
  actions: "Actions",
  connectedProducts: "Connected Products",
  connectedShops: "Connected Shops",
  publishOptions: "Publish Options",
  labelProperties: "Label Properties",
  labelStyle: "Label Style",
  shopsAndProducts: "Shops and Products",
  wait: "Please Wait",
  resources: "Resources",
  goBack: "Go Back",
  enterKeyWork: "Please Enter a Keyword",
  alertTitle: "Are You Sure ?",
  deleteProductAlertText: "Are you sure you want to delete the Product !",
  deleteLabelAlertText: "Are you sure you want to delete the Label !",
  updateLabelAlertText: "Are you sure you want to Update Label Details ?",
  deleteAlertConfirm: "Yes, delete it!",
  updateSuccess: "Label Updated Successfully !",
  deleteSuccess: "Label Deleted Successfully !",
  addSuccess: "Added Successfully",
  ok: "Ok, got it",
  cancel: "Cancel",
  codeNotValidReq: "Code Must be Unique",
  slugNotValidReq: "Slug Must be Unique",
  labelDetails: "Label Details",
  home: "Home",
  thumbnail: "Thumbnail",
  products: "Products",
  shops: "Shops",
  codeNotValid: "Code must be 4 charcters at minimum",
  invalidHex: "This Hex Color is invalid !",
  addBrand: "Add Brand",
  brands: "Brands",
  slug: "slug",
  deleteProductBrandAlertText:
    "Are you sure you want to delete the Product from this Brand ?!",
  deleteBrandAlertText: "Are you sure you want to delete the Brand !",
  updateBrandAlertText: "Are you sure you want to Update Brand information ?",
  brandUpdateSucess: "Brand Updated Successfully !",
  slugNotValid: "Code must be 4 charcters at minimum and unique  ",
  addProduct: "Add Product",
  //Client
  clientGroupAdded: "Successfully Added ",
  deleteclientGroupAlertText: "Are you sure you want to delete  !",
};
