enum Actions {
  // action types
  ADD_BODY_CLASSNAME = "addBodyClassName",
  REMOVE_BODY_CLASSNAME = "removeBodyClassName",
  ADD_BODY_ATTRIBUTE = "addBodyAttribute",
  REMOVE_BODY_ATTRIBUTE = "removeBodyAttribute",
  ADD_CLASSNAME = "addClassName",
  VERIFY_AUTH = "verifyAuth",
  LOGIN = "/Autentication/login",
  SETTINGS = "/Application/get-app-settings",
  COUNTRIES = "/LookupQueries/get-countries",
  LOGOUT = "logout",
  REGISTER = "/Autentication/register",
  USER = "/UserQueries/get-user",
  MARKET = "/MarketQueries/get-market",
  UPDATE_USER = "updateUser",
  FORGOT_PASSWORD = "forgotPassword",
  SET_BREADCRUMB_ACTION = "setBreadcrumbAction",
  CURRENCIES = "/LookupQueries/get-currencies",
  LANGUAGES = "/LookupQueries/get-languages",
  ACCOUNTS_TYPE = "/LookupQueries/get-account-types",
  SHOP_CATEGORIES = "/LookupQueries/get-shop-categories",
  GET_CITY_BY_COUNTRYID = "/LookupQueries/get-country-cities",
  GET_AREA_BY_CITYID = "/LookupQueries/get-city-areas",
  SET_CURRENT_LANGS = "setCurrentLangs",
  SET_SETUP_DATA = "setSetupData",
  SET_SETUP_RESOURCES = "setSetupResources",
  ADD_SETUP_LOGO = "/ManageCommands/upload-file",
  SEND_SETUP_DATA = "/MarketCommands/create-market",
  CATEGORIES = "/ProductCategoryQueries/get-categories",

  UPDATE_MARKET = "/MarketCommands/update-market",
  //Modifier
  GET_MODIFIERS = "/ProductModifierQueries/get-modifiers",
  GET_PRODUCT_Modifiers_BY_ID = "/ProductModifierQueries/get-modifier",
  ADD_MODIFIERS = "/ProductModifierCommands/create-modifier",
  DELETE_PRODUCT_MODIFIERS = "/ProductModifierCommands/remove-modifier",
  UPDATE_MODIFIERS = "/ProductModifierCommands/update-modifier",
  GET_MODIFIER_PRODUCTS = "/ProductModifierQueries/get-modifier-products",
  IS_VALID_CODE_PRODUCT_MODIFIER = "/ProductModifierCommands/is-valid-code",
  ADD_PRODUCTS_TO_MODIFIER = "/ProductModifierCommands/add-products-to-modifier",
  REMOVE_PRODUCTS_FOMR_MODIFIER = "/ProductModifierCommands/remove-products-from-modifier",
  UPLOAD_FILE = "/ManageCommands/upload-file",

  //brands
  GET_PRODUCT_BRANDS = "/ProductBrandQueries/get-brands",
  ADD_PRODUCT_BRANDS = "/ProductBrandCommands/create-productbrand",
  DELETE_PRODUCT_BRANDS = "/ProductBrandCommands/remove-productbrand",
  GET_PRODUCT_BRAND = "/ProductBrandQueries/get-brand",
  EDIT_PRODUCT_BRAND = "/ProductBrandCommands/update-productbrand",
  GET_DETAIL_PRODUCT_BRAND = "/ProductBrandQueries/get-brand-products",
  DELETE_DETAIL_PRODUCT_BRANDS = "/ProductBrandCommands/remove-products-from-brand",
  ADD_DETAIL_PRODUCT_BRANDS = "/ProductBrandCommands/add-products-to-brand",
  SEARCH_PRODUCTS = "/ProductQueries/search-products",
  VARIATIONS_SELECTION_CONTROL_TYPES = "/LookupQueries/product-variation-selection-control-types",
  VARIATIONS_VALUE_TYPES = "/LookupQueries/product-variation-value-types",
  DELIVERY_CLASSES = "/LookupQueries/get-delivery-classes",
  VEHICLE_TYPES = "/LookupQueries/get-vehicle-types",
  VEHICLE_SPECIAL_REQUIREMENTS = "/LookupQueries/get-vehicle-special-requirements",
  DELIVERY_TYPES_CATEGORIES = "/LookupQueries/get-product-delivery-type-categories",
  GET_SHOPS = "/ShopQueries/get-shops",
  ADD_PRODUCT_FOR_LABEL = "/ProductLabelCommands/add-products-to-label",
  REMOVE_PRODUCT_FROM_LABEL = "/ProductLabelCommands/remove-products-from-label",
  FONTAWESOME_ICONS = "/LookupQueries/get-fontawesome-icons",
  GET_PRODUCT_LABELS = "/ProductLabelQueries/get-labels",
  GET_PRODUCT_LABEL = "/ProductLabelQueries/get-label",
  GET_LABEL_SHOPS = "/ProductLabelQueries/get-label-shops",
  GET_LABEL_PRODUCTS = "/ProductLabelQueries/get-label-products",
  ADD_PRODUCT_LABEL = "/ProductLabelCommands/create-productlabel",
  UPDATE_PRODUCT_LABEL = "/ProductLabelCommands/update-productlabel",
  DELETE_PRODUCT_LABEL = "/ProductLabelCommands/remove-productlabel",
  //Categoris
  GET_CATEGORIES = "/ProductCategoryQueries/get-categories",
  ADD_CATEGORIES = "/ProductCategoryCommands/create-productcategory",
  IS_VALID_SLUG_PRODUCT_CATEGORIES = "/ProductCategoryCommands/is-valid-slug",
  GET_CATEGORIE_PRODUCTS = "/ProductCategoryQueries/get-category-products",
  GET_PRODUCT_Categorie_BY_ID = "/ProductCategoryQueries/get-category",
  UPDATE_CATEGORIS = "/ProductCategoryCommands/update-productcategory",
  ADD_PRODUCTS_TO_CATEGORIE = "/ProductCategoryCommands/add-products-to-category",
  DELETE_CATEGORY = "/ProductCategoryCommands/remove-product-categories",
  GET_CATEGORY_PRODUCTS = "ProductCategoryQueries/get-category-products",
  ADD_PRODUCTS_TO_CATEGORY = "/ProductCategoryCommands/add-products-to-category",
  IS_VALID_CODE_PRODUCT_CATEGORY = "/ProductCategoryCommands/is-valid-code",
  REMOVE_PRODUCTS_FOMR_CATEGORY = "/ProductCategoryCommands/remove-products-from-category",
  UPDATE_CATEGORY_PARENT_AND_ORDER = "/ProductCategoryCommands/update-productcategories-order-and-parent",

  //start tags
  GET_PRODUCT_TAGS = "/ProductTagQueries/get-tags",
  GET_PRODUCT_TAG = "/ProductTagQueries/get-tag",
  GET_TAG_SHOPS = "/ProductTagQueries/get-tag-shops",
  GET_TAG_PRODUCTS = "/ProductTagQueries/get-tag-products",
  ADD_PRODUCT_TAGS = "/ProductTagCommands/create-producttag",
  ADD_TAG_DETAILS_PRODUCT = "/ProductTagCommands/add-products-to-tag",
  DELETE_PRODUCT_TAGS = "/ProductTagCommands/remove-producttag",
  SEARCH_PRODUCTS_TAGS = "/ProductQueries/search-products",
  EDIT_PRODUCT_TAG = "/ProductTagCommands/update-producttag",
  REMOVE_PRODUCT_FROM_TAG = "/ProductTagCommands/remove-products-from-tag",
  //end tags

  //Abandoned Carts
  GET_ABANDONED_CARTS = "/LoyaltyQueries/get-abandoned-carts",
  GET_ABANDONED_CART = "/LoyaltyQueries/get-abandoned-cart",
  GET_TIME_UNITS = "/LookupQueries/get-time-units",
  CREATE_ABANDONED_CART = "/LoyaltyCommands/create-abandonedcart-offer",
  GET_ABANDONED_CARTS_OFFERS = "/LoyaltyQueries/get-abandoned-offers",
  REMOVE_ABANDONED_OFFER = "/LoyaltyCommands/remove-abandonedcart-offer",
  GET_OPERATION_TYPES = "/LookupQueries/get-copmerison-opertation-types",
  //Order
  GET_ORDER_STATUS = "/LookupQueries/get-order-statuses",
  ADD_ORDER_ACTION = "/OrderActionsTemplateCommand/create-order-action-template",
  GET_ROLES = "/IdentityQueries/get-roles",
  GET_ORDER_ACTION_TEMPLATE = "/OrderActionsTemplateQuery/get-order-action-templates",
  GET_ORDER_ACTION_TEMPLATE_BY_ID = "/OrderActionsTemplateQuery/get-order-action-template",
  UPDATE_ORDER_ACTION_TEMPLATE = "/OrderActionsTemplateCommand/update-order-action-template",
  DELETE_ORDER_ACTION = "/OrderActionsTemplateCommand/remove-order-action-template",

  //Wishlist
  GET_PRODUCT_WISHLISTS = "/LoyaltyQueries/get-product-wishlists",
  GET_PRODUCT_WISHLIST = "/LoyaltyQueries/get-product-wishlist",

  //Accounts
  GET_ACCOUNTS = "/AccountQueries/get-accounts",
  ADD_ACCOUNT = "/AccountCommands/create-account",
  GET_ACCOUNT_TYPES = "/LookupQueries/get-account-types",
  DELETE_ACCOUNT = "/AccountCommands/remove-account",
  GET_ACCOUNT_SUBTYPES = "/LookupQueries/get-account-subtypes",

  //Wallet
  GET_WALLET_LIST = "/WalletQueries/get-shops-wallets",
  GET_WALLET_BY_ID = "/WalletQueries/get-shop-wallet",
  GET_WALLET_TRANSACTIONS_BY_ID = "/WalletQueries/get-wallet-transactions",
  DEPOSITE_TO_WALLET = "/WalletCommands/deposite-to-wallet",
  WITHDRAW_TO_WALLET = "/WalletCommands/withdraw-from-wallet",
  SET_DEFAULT_ACCOUNT_DEPOSITE = "/WalletCommands/set-default-deposite-account",
  SET_DEFAULT_ACCOUNT_WITHDRAW = "/WalletCommands/set-default-withdraw-account",
  OPERATIONS = "/LookupQueries/get-copmerison-opertation-types",
  CONTROL_TYPES = "/LookupQueries/get-ordering-template-control-types",
  FORMULA_CONDITION_TYPES = "/LookupQueries/get-formula-condition-types",
  PRODUCT_TYPES = "/LookupQueries/get-product-types",
  DIGITAL_DELIVERY_WAYS = "/LookupQueries/get-Digital-product-delivery-ways",
  DIGITAL_PRODUCT_FILE_LOCATION = "/LookupQueries/get-downloadable-digital-product-file-location",
  PRODUCT_TAX_CLASSES = "/LookupQueries/get-product-tax-classes",
  //// Start Point Systems
  GET_POINT_SYSTEMS = "/LoyaltyQueries/get-points-systems",
  FILTER_POINT_SYSTEMS = "/LoyaltyQueries/get-points-systems",
  GET_POINT_SYSTEM = "/LoyaltyQueries/get-points-system",
  ADD_POINT_SYSTEMS = "/LoyaltyCommands/create-points-system",
  UPDATE_POINT_SYSTEMS = "/LoyaltyCommands/update-points-system",
  DELETE_POINT_SYSTEM = "/LoyaltyCommands/remove-points-system",
  //// End Point Systems
}
enum Mutations {
  // mutation types
  SET_CLASSNAME_BY_POSITION = "appendBreadcrumb",
  PURGE_AUTH = "logOut",
  SET_AUTH = "setAuth",
  SET_USER = "setUser",
  SET_MARKET = "SET_MARKET",
  SET_PASSWORD = "setPassword",
  SET_ERROR = "setError",
  SET_BREADCRUMB_MUTATION = "setBreadcrumbMutation",
  SET_LAYOUT_CONFIG = "setLayoutConfig",
  RESET_LAYOUT_CONFIG = "resetLayoutConfig",
  OVERRIDE_LAYOUT_CONFIG = "overrideLayoutConfig",
  OVERRIDE_PAGE_LAYOUT_CONFIG = "overridePageLayoutConfig",
  SET_COUNTRIES = "SET_COUNTRIES",
  SET_SETTINGS = "SET_SETTINGS",
  COUNTRIES = "GET_COUNTRIES",
  SELECTED_COUNTRY = "SELECTED_COUNTRY",
  CURRENCIES = "SET_CURRENCIES",
  LANGUAGES = "SET_LANGUAGES",
  ACCOUNTS_TYPE = "SET_ACCOUNTS_TYPE",
  SHOP_CATEGORIES = "SET_SHOP_CATEGORIES",
  SET_CITIES = "SET_CITIES",
  SET_AREAS = "SET_AREAS",
  SET_CURRENT_LANGS = "SET_CURRENT_LANGS",
  SET_SETUP_DATA = "SET_SETUP_DATA",
  SET_SETUP_RESOURCES = "SET_SETUP_RESOURCES",
  ADD_SETUP_LOGO = "ADD_SETUP_LOGO",
  UPDATE_MARKET = "UPDATE_MARKET",
  GET_SHOPS = "GET_SHOPS",
  BRANDS = "SET_BRANDS",
  DELIVERY_CLASSES = "SET_DELIVERY_CLASSES",
  CATEGORIES = "SET_CATEGORIES",
  VEHICLE_TYPES = "SET_VEHICLE_TYPES",
  VEHICLE_SPECIAL_REQUIREMENTS = "SET_VEHICLE_SPECIAL_REQUIREMENTS",
  DELIVERY_TYPES_CATEGORIES = "SET_DELIVERY_TYPES_CATEGORIES",

  //Modifier
  UPDATE_MODIFIERS = "UPDATE_MODIFIERS",
  GET_MODIFIER_PRODUCTS = "GET_MODIFIER_PRODUCTS",
  VARIATIONS_SELECTION_CONTROL_TYPES = "VARIATIONS_SELECTION_CONTROL_TYPES",
  VARIATIONS_VALUE_TYPES = "SET_VARIATIONS_VALUE_TYPES",
  SET_PRODUCTS_LIST = "SET_PRODUCTS_LIST",
  UPDATE_MODIFIER_PRODUCTS = "UPDATE_MODIFIER_PRODUCTS",
  UPDATE_CURRENT_PAGE = "UPDATE_CURRENT_PAGE",
  UPDATE_PAGINATION = "UPDATE_PAGINATION",
  GET_MODIFIERS = "GET_MODIFIERS",
  ADD_MODIFIERS = "ADD_MODIFIERS",
  GET_PRODUCT_Modifiers_BY_ID = "GET_PRODUCT_Modifiers_BY_ID",
  ISVALID_CODE_MODIFIER = "ISVALID_CODE_MODIFIER",
  SET_MESSAGE_ISVALIDCODE_MODIFIER = "SET_MESSAGE_ISVALIDCODE_MODIFIER",
  UPDATE_CURRENT_PAGE_MODIFIER = "UPDATE_CURRENT_PAGE_MODIFIER",
  UPDATE_PAGINATION_MODIFIER = "UPDATE_PAGINATION_MODIFIER",

  DELETE_PRODUCT_MODIFIERS = "DELETE_PRODUCT_MODIFIERS",
  FILTER_MODIFIER_PRODUCTS = "FILTER_MODIFIER_PRODUCTS",
  // Brands
  SET_PRODUCT_BRANDS = "SET_PRODUCT_BRANDS",
  SET_PRODUCT_BRAND = "SET_PRODUCT_BRAND",
  SET_DETAIL_PRODUCT_BRAND = "SET_DETAIL_PRODUCT_BRAND",
  CREATE_PRODUCT_BRANDS = "CREATE_PRODUCT_BRANDS",
  REMOVE_PRODUCT_BRANDS = "REMOVE_PRODUCT_BRANDS",
  REMOVE_DETAIL_PRODUCT_BRANDS = "REMOVE_DETAIL_PRODUCT_BRANDS",
  UPDATE_PRODUCT_BRAND = "UPDATE_PRODUCT_BRAND",
  CREATE_DETAIL_PRODUCT_BRANDS = "CREATE_DETAIL_PRODUCT_BRANDS",
  SET_SEARCH_PRODUCTS = "SET_SEARCH_PRODUCTS",
  UPDATE_TABLE_PRODUCT = "UPDATE_TABLE_PRODUCT",

  //Labels
  UPDATE_LABEL_PRODUCTS = "UPDATE_LABEL_PRODUCTS",
  ADD_PRODCUCT_LABEL = "addProductLabel",
  SET_PRODUCT_LABELS = "SET_LABELS",
  SET_PRODUCT_LABEL = "SET_LABEL",
  DELETE_PRODUCT_LABEL = "DELETE_LABEL",
  SET_LABEL_SHOPS = "SET_LABEL_SHOPS",
  FILTER_LABEL_PRODUCTS = "FILTER_LABEL_PRODUCTS",
  SET_ICONS = "SET_ICONS",
  SET_LABEL_PRODUCTS = "SET_LABEL_PRODUCTS",
  SET_OPERATIONS = "SET_OPERATIONS",
  CONTROL_TYPES = "SET_CONTROL_TYPES",

  FORMULA_CONDITION_TYPES = "SET_FORMULA_CONDITION_TYPES",
  PRODUCT_TYPES = "SET_PRODUCT_TYPES",
  DIGITAL_DELIVERY_WAYS = "SET_DIGITAL_DELIVERY_WAYS",
  DIGITAL_PRODUCT_FILE_LOCATION = "SET_DIGITAL_PRODUCT_FILE_LOCATION",
  PRODUCT_TAX_CLASSES = "SET_PRODUCT_TAX_CLASSES",
  //Categoris
  GET_CATEGORIES = "GET_CATEGORIES",
  ADD_CATEGORIES = " ADD_CATEGORIES",
  ISVALID_SLUG = "ISVALID_SLUG",
  SET_MESSAGE_ISVALID = "SET_MESSAGE_ISVALID",
  GET_CATEGORIE_PRODUCTS = "GET_CATEGORIE_PRODUCTS",
  SET_PRODUCT_Categorie_BY_ID = "SET_PRODUCT_Categorie_BY_ID",
  GET_CATEGORIES_LIST = "GET_CATEGORIES_LIST",
  GET_CATEGORY_PRODUCTS = "GET_CATEGORY_PRODUCTS",
  UPDATE_CATEGORY_PRODUCT = "UPDATE_CATEGORY_PRODUCT",
  SET_MESSAGE_ISVALIDCODE = "SET_MESSAGE_ISVALIDCODE",
  ISVALID_CODE = "ISVALID_CODE",

  //start tags
  SET_PRODUCT_TAGS = "SET_PRODUCT_TAGS",
  SET_TAG_PRODUCTS = "SET_TAG_PRODUCTS",
  SET_PRODUCT_TAG = "SET_PRODUCT_TAG",
  SET_TAG_SHOPS = "SET_TAG_SHOP",
  CREATE_PRODUCT_TAGS = "CREATE_PRODUCT_TAGS",
  REMOVE_PRODUCT_TAGS = "REMOVE_PRODUCT_TAGS",
  CREATE_TAG_DETAILS_PRODUCT = "CREATE_TAG_DETAILS_PRODUCT",
  SET_SEARCH_PRODUCTS_TAGS = "SET_SEARCH_PRODUCTS",
  UPDATE_PRODUCT_TAG = "UPDATE_PRODUCT_TAG",
  DELETE_PRODUCT_FROM_TAG = "DELETE_PRODUCT_FROM_TAG",
  UPDATE_TABLE_PRODUCT_TAGS = "UPDATE_TABLE_PRODUCT",
  UPDATE_TAG_PAGINATION = "UPDATE_TAG_PAGINATION",
  UPDATE_TAG_CURRENT_PAGE = "UPDATE_TAG_CURRENT_PAGE",
  RESET_PAGINATION_TAGS = "RESET_PAGINATION_TAGS",

  //end tags

  //Abandoned Carts
  SET_ABANDONED_CARTS = "SET_ABANDONED_CARTS",
  SET_ABANDONED_CART = "SET_ABANDONED_CART",
  SET_TIME_UNITS = "SET_TIME_UNITS",
  SET_ABANDONED_CARTS_OFFERS = "SET_ABANDONED_CARTS_OFFERS",
  SET_OPERATION_TYPES = "SET_OPERATION_TYPES",
  //Order
  SET_ORDER_STATUS = "SET_ORDER_STATUS",
  SET_ROLES = "SET_ROLES",
  SET_ORDER_ACTION_TEMPLATE = "SET_ORDER_ACTION_TEMPLATE",
  UPDATE_PAGINATION_ORDER = "UPDATE_PAGINATION_ORDER",

  //Wishlist
  SET_PRODUCT_WISHLISTS = "SET_PRODUCT_WISHLISTS",
  SET_PRODUCT_WISHLIST = "SET_PRODUCT_WISHLIST",

  //Accounts
  SET_ACCOUNTS = "SET_ACCOUNTS",
  ADD_ACCOUNT = "ADD_ACCOUNT",
  SET_ACCOUNT_TYPES = "SET_ACCOUNT_TYPES",
  SET_ACCOUNT_SUBTYPES = "SET_ACCOUNT_SUBTYPES",
  DELETE_ACCOUNT = "DELETE_ACCOUNT",

  //Wallet
  SET_WALLET_LIST = "SET_WALLET_LIST",
  SET_WALLET_DETAILS = "SET_WALLET_DETAILS",
  SET_WALLET_TRANSACTIONS_BY_ID = "SET_WALLET_TRANSACTIONS_BY_ID",
  UPDATE_TRANSACTION_TABLE = "UPDATE_TRANSACTION_TABLE",
  UPDATE_CURRENT_PAGE_TRANSACTION_TABLE = "UPDATE_CURRENT_PAGE_TRANSACTION_TABLE",

  //// Start Point Systems
  SET_POINT_SYSTEMS = "SET_POINT_SYSTEMS",
  SET_POINT_SYSTEM = "SET_POINT_SYSTEM",
  //// End Point Systems
}

export { Actions, Mutations };
